// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xdgmgzjhmrzwztkpurow.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhkZ21nempobXJ6d3p0a3B1cm93Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI3MzA5ODYsImV4cCI6MjA3ODMwNjk4Nn0.JGm_Ym78FN9nC5pvNaaEuj9hJvUDasOr3B3ImRIPYoI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});